apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database-service
  namespace: default
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: database
  sessionAffinity: None
  type: ClusterIP
