apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpressweb
  name: wordpressweb
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordpressweb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpressweb
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              key: dbhost
              name: wp-configmap
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: wp-configmap
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: wp-configmap
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: wp-configmap
        image: wordpress:latest
        imagePullPolicy: Always
        name: mysql-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
