apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpressweb
  name: web-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpressweb
  sessionAffinity: None
  type: LoadBalancer
